### PR TITLE
Adding support for org-mode table input/output

### PR DESCRIPTION
**Pull request by jtmoulia**

### CODE REVIEW

**Comment by victorolinasc** [comment]
I am trying to get a working example with your code and am failing to get it working. Could you paste an example? I mean, following babel's documentation [here](http://orgmode.org/worg/org-contrib/babel/intro.html), this should work:

``` org-mode
#+tblname: fibonacci-inputs
| 1 | 2 | 3 | 4 |  5 |  6 |  7 |  8 |  9 | 10 |

#+name: fibonacci-seq
#+begin_src elixir :exports both :var fib-inputs=fibonacci-inputs 
IO.puts "#{inspect fib-inputs}"
#+end_src
```

Or am I getting it wrong? Sorry for the newbie in org-mode syntax here.

Cheers

**Comment by jtmoulia** [comment]
I think the issue is that `fib-inputs` isn't a valid variable name in elixir -- try

```
#+tblname: fibonacci-inputs
| 1 | 2 | 3 | 4 |  5 |  6 |  7 |  8 |  9 | 10 |

#+name: fibonacci-seq
#+begin_src elixir :exports both :var fib_inputs=fibonacci-inputs 
  IO.inspect fib_inputs
#+end_src
```

Thanks for looking!

**Comment by jtmoulia** [comment]
[Here's](http://jtmoulia.pocketknife.io/blog/2015/03/15/about-ob-elixir/) how I tested it.

**Comment by victorolinasc** [comment]
You are right! My bad!

WIll merge it right now! Thanks a lot!

**Comment by jtmoulia** [comment]
awesome, thanks!

**Pull request merged**
